# Generated by Django 4.1 on 2022-09-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='breakfast',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meals',
            name='dinner',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meals',
            name='lunch',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userintreface',
            name='toEat',
            field=models.IntegerField(default=0),
        ),
    ]
