# Generated by Django 4.1 on 2022-09-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMenu', '0002_alter_meals_breakfast_alter_meals_dinner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='userCreated',
        ),
        migrations.AlterField(
            model_name='userintreface',
            name='username',
            field=models.CharField(default='a4ch3r', max_length=100),
        ),
    ]
