# Generated by Django 4.1 on 2022-09-11 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMenu', '0003_remove_product_usercreated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meallist',
            name='date',
            field=models.DateField(default=datetime.date(2022, 9, 11)),
        ),
        migrations.AddField(
            model_name='meals',
            name='date',
            field=models.DateField(default=datetime.date(2022, 9, 11)),
        ),
    ]
